### ISSUE TITLE
Any JsFunction Example?

### ISSUE THREAD

**Issue by nickming** [ohos-rs/example#1]
Any JsFunction Example?

**Comment by southorange0929** [comment]
I'm not sure if you want code like the [hello example](https://github.com/ohos-rs/example/blob/main/example/hello/src/lib.rs). If not, can you provide some scenarios?

**Comment by nickming** [comment]
主要是想请教关于js_function宏的使用方法，我看demo中没有export的ts函数声明文件，导致无法匹配上类型；同时想请教create_threadsafe_function的用法，目前测试下来返回的都是null

**Comment by southorange0929** [comment]
1. js_function宏 可以参考这个 [示例](https://github.com/ohos-rs/example/blob/main/example/arraybuffer/src/lib.rs)
2. 类型生成是在构建阶段做的，现在还在开发中。预计月底新的脚手架会支持，可以新提一个Issue跟进
3. [tsfn 示例](https://github.com/ohos-rs/example/blob/main/example/tsfn/src/lib.rs#L12)

**Comment by southorange0929** [comment]
其他问题 可以新提Issue 这个先关闭了

**Comment by nickming** [comment]
> 1. js_function宏 可以参考这个 [示例](https://github.com/ohos-rs/example/blob/main/example/arraybuffer/src/lib.rs)
> 2. 类型生成是在构建阶段做的，现在还在开发中。预计月底新的脚手架会支持，可以新提一个Issue跟进
> 3. [tsfn 示例](https://github.com/ohos-rs/example/blob/main/example/tsfn/src/lib.rs#L12)

根据最新的demo测试，tsfn回调的值一直是null，这个请问你那边有出现吗

**Comment by southorange0929** [comment]
> > 1. js_function宏 可以参考这个 [示例](https://github.com/ohos-rs/example/blob/main/example/arraybuffer/src/lib.rs)
> > 2. 类型生成是在构建阶段做的，现在还在开发中。预计月底新的脚手架会支持，可以新提一个Issue跟进
> > 3. [tsfn 示例](https://github.com/ohos-rs/example/blob/main/example/tsfn/src/lib.rs#L12)
> 
> 根据最新的demo测试，tsfn回调的值一直是null，这个请问你那边有出现吗

应该是镜像问题，跟napi_typeof有点类似 我确认下。

**Comment by nickming** [comment]
> > > 1. js_function宏 可以参考这个 [示例](https://github.com/ohos-rs/example/blob/main/example/arraybuffer/src/lib.rs)
> > > 2. 类型生成是在构建阶段做的，现在还在开发中。预计月底新的脚手架会支持，可以新提一个Issue跟进
> > > 3. [tsfn 示例](https://github.com/ohos-rs/example/blob/main/example/tsfn/src/lib.rs#L12)
> > 
> > 
> > 根据最新的demo测试，tsfn回调的值一直是null，这个请问你那边有出现吗
> 
> 应该是镜像问题，跟napi_typeof有点类似 我确认下。

期待大佬解决，补充完这个case，全流程看起来就没啥问题了

**Comment by southorange0929** [comment]
参考 https://github.com/ohos-rs/example/blob/main/ohos_rs_example/entry/src/main/ets/pages/Tsfn.ets#L16
参数必须使用剩余参数表达式接受，不支持一个个变量直接接受。会被方舟编译器优化掉。 @nickming

**Comment by nickming** [comment]
看起来都没问题了，强

**Comment by southorange0929** [comment]
另外注意下 使用的方法。如果是带错误的，第一个参数就是err 无报错就是null

**Comment by meloalright** [comment]
看起来如果基于 tsFn 的示例，必须得是同一类型的 `Vec<T>` 例如 `Vec<JsNumber>` 或者 `Vec<JsString>` 之类的。
实际上 Arkts 那边的 Function 可能是不同类型 比如 `(text: string, num: number) => void`

有什么解决示例嘛？ @richerfu

**Comment by richerfu** [comment]
1.0.3 以及之前的版本可以直接定义元组。
1.0.4 版本可以只用`FnArgs`。

```rs
ThreadsafeFunction<(String, i32), ()>

ThreadsafeFunction<FnArgs<(String, i32)>, ()>
```

@meloalright
