### ISSUE TITLE
Can't get OHOS_NDK_HOME.: NotPresent

### ISSUE THREAD

**Issue by mdddj** [ohos-rs/example#18]
有目录参考一下吗,一直不成功...
<img width="371" alt="image" src="https://github.com/ohos-rs/example/assets/29020213/641164a8-c7fd-48dd-a9b0-b394167852db">
<img width="582" alt="image" src="https://github.com/ohos-rs/example/assets/29020213/074d73b8-7519-43b2-8b30-294b2eca55e4">

**Comment by richerfu** [comment]
@mdddj Sdk/9 这个路径。最终的目录结构如下所示：
<img width="679" alt="image" src="https://github.com/ohos-rs/example/assets/32590310/5c31b262-3a1f-461e-a6b4-ad2e8932842b">

**Comment by mdddj** [comment]
配置了也不行,识别不到环境变量
<img width="502" alt="image" src="https://github.com/ohos-rs/example/assets/29020213/4d76123d-d0eb-4884-9be0-419826a439b9">
<img width="525" alt="image" src="https://github.com/ohos-rs/example/assets/29020213/866955eb-9920-4e82-bf8e-f6d01aafb050">

**Comment by richerfu** [comment]
> 配置了也不行,识别不到环境变量
> <img width="502" alt="image" src="https://github.com/ohos-rs/example/assets/29020213/4d76123d-d0eb-4884-9be0-419826a439b9">
> <img width="525" alt="image" src="https://github.com/ohos-rs/example/assets/29020213/866955eb-9920-4e82-bf8e-f6d01aafb050">
> 

已确认 环境配置问题
