### ISSUE TITLE
option<T>和Buffer问题是否已经修复？

### ISSUE THREAD

**Issue by lubinglun** [ohos-rs/example#4]
您好！请问在README.md中提到的这两个错误，是否已经官方接纳并修复？如果没有，请问如何复现该类错误？
> 2. 为什么 Option<T> 参数会报错？
> 目前OpenHarmony NDK中的 napi_typeof 方法实现有点问题，对于可选参数无法默认处理成 undefined 值。已向团队提相关问题，待修复即可。
> 
> 3. 为什么 Buffer 在 Native 和 ArkTS 之间无法直接传递？
> ArkTS侧的 buffer实现跟Native侧的 Buffer实现不一致，导致在跨语言传递的时候出现问题。已向官方提相关问题，待修复即可。

**Comment by southorange0929** [comment]
不好意思回复太晚。
1. 对于`Option<T>`的问题 应该是跟当前手机的ROM 版本有关，也就是说有些版本可能不是必现的，使用`Option<T>`如果不传值的时候报错了，传值又没报错。就是这个问题
2. 这个短期内估计不太会修复，涉及到ArkTS侧的API大量变更
